name: Progetto Web CI Pipeline

# 1. La pipeline parte ad ogni push sul branch principale
on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

# 2. --- Lista dei Job da eseguire ---
jobs:
  # JOB 1: Test delle dipendenze nel Backend Node.js
  build-backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    
    steps:
    # A. Scarica il codice dalla repo
    - name: Checkout del codice
      uses: actions/checkout@v4

    # B. Prepara l'ambiente Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: './Back/package-lock.json'

    # C. Installa le dipendenze
    - name: Installa dipendenze Backend
      working-directory: ./Back
      run: npm ci

  # JOB 2: Build del Frontend Angular
  build-frontend:
    name: Build Frontend Angular
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: './Front/Front-app/package-lock.json'

    - name: Installa dipendenze Frontend
      working-directory: ./Front/Front-app
      run: npm ci

    # A. Compila Angular in modalit√† produzione per verificare che non ci siano errori TypeScript
    - name: Compila Angular (Production)
      working-directory: ./Front/Front-app
      run: npm run build --configuration=production

  # JOB 3: Continuous Delivery con DockerHub
  docker-build-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    
    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    # 1. Login sicuro su Docker Hub usando le variabili d'ambiente
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 2. Compila, tagga e invia il Backend
    - name: Build and Push Backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/webapp-backend:latest ./Back
        docker push ${{ secrets.DOCKER_USERNAME }}/webapp-backend:latest

    # 3. Compila, tagga e invia il Frontend
    - name: Build and Push Frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/webapp-frontend:latest ./Front/Front-app
        docker push ${{ secrets.DOCKER_USERNAME }}/webapp-frontend:latest